theme: jekyll-theme-minimal
title: Mafalda Dias
description: "Postodoctoral Researcher<br/>
Systems Biology Department<br/>
Harvard Medical School<br/>
<br/>
mafalda_dias@hms.harvard.edu
<br/>
<a href="https://github.com/mafaldadias">github profile</a>"
logo: assets/images/ware3.jpg
