theme: jekyll-theme-minimal
title: Mafalda Dias
description: "Postodoctoral Researcher<br/>
Systems Biology Department<br/>
Harvard Medical School<br/>
<br/>
mafalda_dias@hms.harvard.edu
<br/>
<link href='https://github.com/mafaldadias' rel='github profile'>
[github profile](https://github.com/mafaldadias)"
logo: assets/images/ware3.jpg
